name = "Server Pack Master"
author = "Jesus NR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cab7a32fe440d55dcf74b6124c22dcb03666162ddd5a61f64bb8293b0e2e772"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
