name = "Server Pack Master"
author = "Jesus NR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d890b418ae36f134cec058ff2d721eb2747bb991fd15905d05bae6906fc32e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
