name = "Server Pack Master"
author = "Jesus NR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1322d694702a085e7f4c1119a1fa72ac86e3ae056b835ba7fcf070318ef816c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
