name = "Server Pack Master"
author = "Jesus NR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f0fa7a56a87a65892c3c130204526fe570eb0dc262930f7ca71f01176db802"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
